sudo: required
services:
  - docker

env:
  global:
    - secure: i7HxqwyHeosmxNpp0Sr6ybnh2E7BjcpcKd/q/wznVWNOc0+grnQ7mCitEHd05FCI5DrCgoOWRdiNPVt5XE9X5jD+LkoRe3Tsr/6fFGOJGzEsRdInosCo5MguI6EIescpqGePcJsXI3u98axTv8cfU7NkYEulMcZODPxK1nOJ/BfpK5VbGats0BSdmdwToZNetxmQivtZ37yoGyO4yjVFxljlsCO9uASVMhuoxxzpVGak4I11FlOismoC8RhJ6SaoYJnyn0aaqE7V6gDETHNZ4vGOv/yHCeWo/MedAyHEt150InzgqmU13nud4oJkDJ5xyCabzcC+cRXYR+5nTnISr4MAh2mwF4VLAiVaufFXM8DfqUCcC9rBkyz1BiQHkhD6YVX76HHQ7j97dN3Nmjz7Y+5MgHLVRMqjSrVhPPJQLFh9k0YKZt2FRQWoTvUYiFdtpN46xmHU5fYscKbtvjKLx21U/o+BsUyypecbXlgAy8PD+gLZa05YFKaxag2Y+iDAywxiH6AjRpjEk1O+I9ABtMMk0NqVmCvDwBRgDT1TM/ax9TYQfU3iStFwSvd72QSFSwFGzs5CC5wqYzC2hBxnLeR3EhH9z2CvRh6g03GJtTQ4FSaVc9ZML/1ooTEvFw0lQIz9Bg2Np45oeYiTNZh0pWNUqI4WWAUDfuNoh/Pq7N8= # DOCKER_EMAIL
    - secure: WU9tOzOastOj3SJt0v8TjDQSLcZ1T5vcb9Rl2WSzdSzxQ+92VQJaL+VNhZ2pIt3f5mQZRhb1Ms0aD6jMZjZ6ELqwki3vhcFvO9IFz15LW3UeRitWRuk7bDftuA1ghsWuJdwFQzIosS96FmqsqgwE5yCZbzLiJ4xouWKZ5tibB+0mUQnXDBhe9bfeVPBtg1xoqF2SiAvyZ06kz2LH1ngCJ8Ex7c2epA0J0Gso5B61c2TVbOVX0wx8DapVSn7ia9a318/7bA8tMF7UiZ+tePQoY6MYT7bjrdVVmZ0lk57Z7Io87sDTSKNfjK2svChssbzDPrudJgFBBGDUNBV3/3DWA6LiAOS/O84ZI5Wdfc/g7WV4VBYof3gHBVYCoBaqfopHl+KF6tjvRRNNMk8oUaJH6Nq/SkiSwjjMBvDNNYWprAUPw4JPhrENFNVU31icuRNHYdYGWWmHgd2YZKUggfaapyaHbTsISaabI3ZRep1vCHuRo+ebHSi8ERxy8DgjC6O0drB5RCUavBowGHymW2kH94rLop1OhaT2WedDL8dEHOKyXkFoVQ848D9mo21ari+01BsgA8bwuRRPRzMpUx0lbLlcUa1yJA2WxW3kv6tuJMHsg3ELEYnBDFTS2q9ZhsW3NPdsfZ8ZmypN7y9ylDN1KC3+xvht9GMVgXS2F0te8Lc= # DOCKER_USER
    - secure: OXkKxeYXy3uVyLk9v3k9sgMBWvYflhKBZWjaPGe48WvLsiRZLIWBkc7UK22IekbMPuO2bnH3lVIGlT+2n6pNjsb/HAQ/z6n3Bsd7mUsQved9G0pUeTLtna3lKLmW9DUmUHAd9aq8CoQOR+K3jCA0Dt+5cIc0Go+AFQCQMZH5oSdGk8nUw4RlxpgujqldkEUPXtLpXyIMMQooAyY2aPDLb2Kotwf/siXwZ5hmelAg9E6A/URYTlhCdxKbDGd3YzFBJK3jRWCaYYRXBDw92S7baF9jfHpDbpYGa+kNNDa8oKC2KIub4ACgWdKtaY6ZULlHq2oUYueARJajP/DdKYIYu/KLtmMHJgMTOhaNO/MOtpKtkTpm9AsdEsT1s11ntBe149jJxbuET7oYMVhB4ZJ594W3jks+OY4HvAB6mRtkqtnDQR9JZ6IawoWCr+VNTy65MnQhyu6fpBQ0bE+gssMzoqPipGKD/Iig7I0C4lvTP7wkWMhn16tCx72NabfGI79SMN8t3mjLofH98qksZvguEQjGw39mqNHvwvpwEZg7gIR3qd36kcOg1cikj2F5t7ku8pTvVgXQIjv6r43wm6Q3BQI9J6zMIjRIYP+xMCpAVL8rCfubdQ8ZEfV1k3OBEGLBLZur28Lxv2BqcPXyB9iXw0J4txUxt3+D3LX9xmNICOM= # DOCKER_PASSWORD

before_install:
  - docker-compose build

script:
  - docker-compose run tests

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO=blpeterjr/gbr-mern
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master"]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
