import { users } from "react-icons-kit/icomoon/users";
import { logout } from "react-icons-kit/iconic/logout";
import { calendar } from "react-icons-kit/icomoon/calendar";
import { list2 } from "react-icons-kit/icomoon/list2";
import { ic_shopping_cart } from "react-icons-kit/md/ic_shopping_cart";
import { home3 } from "react-icons-kit/icomoon/home3";
import { folder } from "react-icons-kit/ikons/folder";
import { box } from "react-icons-kit/iconic/box";
import { ic_keyboard_tab } from "react-icons-kit/md/ic_keyboard_tab";
import { ic_keyboard_backspace } from "react-icons-kit/md/ic_keyboard_backspace";
import { userPlus } from "react-icons-kit/fa/userPlus";
import { search } from "react-icons-kit/fa/search";
import { menu } from "react-icons-kit/icomoon/menu";
import { ic_close } from "react-icons-kit/md/ic_close";
import { userCircle } from "react-icons-kit/fa/userCircle";
import { arrowLeft } from "react-icons-kit/fa/arrowLeft";
import { arrowRight } from "react-icons-kit/fa/arrowRight";

export const CustomersIcon = users;
export const ContainersIcon = box;
export const ProductsIcon = ic_shopping_cart;
export const QuotesIcon = list2;
export const CalendarIcon = calendar;
export const OrdersIcon = folder;
export const DashboardIcon = home3;
export const LogoutIcon = logout;
export const CollapsedIcon = ic_keyboard_tab;
export const notCollapsedIcon = ic_keyboard_backspace;
export const addCustomerIcon = userPlus;
export const SearchIcon = search;
export const MenuIcon = menu;
export const CloseIcon = ic_close;
export const AccountIcon = userCircle;
export const ArrowLeft = arrowLeft;
export const ArrowRight = arrowRight;
